 const types={
     /*
        play page
     */
    FETCH_DATA_PLAY:'FETCH_DATA_PLAY',
    PLAY_LOADING_STATUS:'PLAY_LOADING_STATUS',
    FETCH_BANNER_PLAY:'FETCH_BANNER_PLAY',
    BANNER_HANDLED:'BANNER_HANDLED',
    SAVE_BANNER:'SAVE_BANNER',
    /*
        counter page
     */
    INCREMENT_COUNTER:'INCREMENT_COUNTER',
    DECREMENT_COUNTER:'DECREMENT_COUNTER',
    FETCH_DATA_COUNTER:'FETCH_DATA_COUNTER',
    /*
        frame
    */
    FETCH_FRAME_DATA:'FETCH_FRAME_DATA',
    SHOW_ERROR_MODAL:'SHOW_ERROR_MODAL',
    CLOSE_ERROR_MODAL:'CLOSE_ERROR_MODAL',
    SHOW_SUCCESS_TOAST:'SHOW_SUCCESS_TOAST',
    HIDE_SUCCESS_TOAST:'HIDE_SUCCESS_TOAST',
    /*
    mine
    */
    FETCH_MINE_DATA:'FETCH_MINE_DATA',
    /*
    welfare
    */
    FETCH_WELFARE_DATA:'FETCH_WELFARE_DATA',

    /*
    *addmovie
    */
    ADD_MOVIE:'ADD_MOVIE',
    ADD_MOVIE_ERROR:'ADD_MOVIE_ERROR',
    GET_QINIU_TOKEN:'GET_QINIU_TOKEN',
    /**
     * learn record
    */
    ADD_LEARN_RECORD:'ADD_LEARN_RECORD',
    LEARN_RECORD_LIST:'LEARN_RECORD_LIST',
    UPDATE_LEARN_RECORD:'UPDATE_LEARN_RECORD',
    /**
     * user login
    */
    USER_LOGIN:'USER_LOGIN',
    USER_LOGOUT:'USER_LOGOUT',
}
export default types